name: DanaRanks
version: '${project.version}'
main: app.danakube.danaranks.core.DanaRanks
api-version: '1.21'
description: Plugin de gestion des rangs pour le serveur DanaKube.
author: DanaKube

dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
    Vault:
      load: BEFORE
      required: false

commands:
  danaranks:
    description: Commande d'administration principale de DanaRanks.
    permission: danaranks.admin
    aliases: [dr]
  profile:
    description: Ouvre le profil du joueur.
    aliases: [ranks]
  quota:
    description: Ouvre les quotas du joueur.
  leaderboard:
    description: Ouvre le classement global.
    aliases: [top]


