name: DanaRanks
version: '${project.version}'
main: app.danakube.danaranks.core.DanaRanks
api-version: '1.21'
description: Plugin de gestion des rangs pour le serveur DanaKube.
author: DanaKube

dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
    Vault:
      load: BEFORE
      required: false


